service: lunch-lambda

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  save-lunch:
    cljs: lunch-lambda.core/save-lunch
    events:
      - http:
          path: save-lunch
          method: post

resources:
  Resources:
    lunchTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lunchTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
plugins:
  - serverless-cljs-plugin
